### ISSUE TITLE
Flow Control

### ISSUE THREAD

**Issue by overkillthemighty** [Daniel-dev22/esphome-econet#24]
Does/can your library define a flow control pin for use with a max485 chip? It is essentially just a pin that goes high when you are transmitting and low to receive.

**Comment by Daniel-dev22** [comment]
Esphome can do that. This is a component that runs on esphome. 

https://esphome.io/components/modbus.html#configuration-variables

**Comment by overkillthemighty** [comment]
I have a well pump controller I control with modbus and I use it with that. I was asking because in the example code it passes a uart and not a modbus reference. Should I be passing it a modbus reference here for my use?
`uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: 
    number: ${tx_pin}
  rx_pin:
    number: ${rx_pin}

econet:
  uart: uart_0
  model: "Tankless"`

**Comment by Daniel-dev22** [comment]
> I have a well pump controller I control with modbus and I use it with that. I was asking because in the example code it passes a uart and not a modbus reference. Should I be passing it a modbus reference here for my use? `uart: id: uart_0 baud_rate: 38400 rx_buffer_size: 1500 tx_pin: number: ${tx_pin} rx_pin: number: ${rx_pin}
> 
> econet: uart: uart_0 model: "Tankless"`

`Modbus RTU is a straightforward serial protocol that may be sent using standard UART technology`

It's still modbus.

**Comment by overkillthemighty** [comment]
I understand that. I am asking how to define a pin (say GPIO 22) as the flow control pin while using your library. This does not work:

> external_components:
>   - source: github://Daniel-dev22/esphome-econet
>   # - source: components
> 
> uart:
>   id: uart_0
>   baud_rate: 38400
>   rx_buffer_size: 1500
>   tx_pin: 
>     number: ${tx_pin}
>   rx_pin:
>     number: ${rx_pin}
> 
> modbus:
>   flow_control_pin: GPIO22
>   id: modbus1
> 
> econet:
>   uart: uart_0
>   model: "Tankless"
> 
> climate:
>   - platform: econet
>     name: "Water Heater"
> 
> sensor:
>   - platform: econet
>     temp_in:
>       name: "Temperature In"
>     temp_out:
>       name: "Temperature Out"
>     setpoint:
>       name: "Set Point Temperature"
>     btus_used:
>       name: "BTUs Used"
>     water_used:
>       name: "Water Used"
>     flow_rate:
>       name: "Flow Rate"
>     ignition_cycles:
>       name: "Ignition Cycles"
> 
> binary_sensor:
>   - platform: econet
>     enable_state:
>       name: "Water Heater Enabled (Sensor)"




I know this setup works as this was my test rig for getting the pentair controller working. I do not have an oscilliscope with me at the moment, so I can not check if that GPIO is actually doing anything. I imagine it is not though as this is what I am getting:

> Name	State	Actions
> BTUs Used	0.000 kbtu	
> Flow Rate	0.0 gpm	
> Ignition Cycles	0	
> Set Point Temperature	0.0 °F	
> Temperature In	0.0 °F	
> Temperature Out	0.0 °F	
> Water Heater	-18	Current: -18, Target: -18
> 27 
>  4838889
> Mode:
> 
> OFF
> Water Heater Enabled (Sensor)	OFF	
> Water Used	0.0 gal

**Comment by Daniel-dev22** [comment]
If you have any additional questions I would consider joining the [discord](https://discord.gg/MtEsC77xRg) this repo is being archived in favor of consolidating code [here](https://github.com/esphome-econet/esphome-econet).
