### ISSUE TITLE
Expose Alerts via Econet-Esphome

### ISSUE THREAD

**Issue by barndawgie** [Daniel-dev22/esphome-econet#25]
My water heater had an active alert due to need for a filter cleaning. Is there anyway these could be exposed via this integration, or are those alerts not present on the bus?

**Comment by Daniel-dev22** [comment]
> 

Do you have logs of this alert from the bus?

**Comment by barndawgie** [comment]
How would I capture this? Will the esphome-econet logs capture raw bus output or only parsed/looked for messages/codes?

**Comment by Daniel-dev22** [comment]
If the alert is still active and you have a heatpump we should see something if you compile the dev branch I just added something.

**Comment by barndawgie** [comment]
I (stupidly) cleared the alert.

**Comment by Daniel-dev22** [comment]
> I (stupidly) cleared the alert.

Oh ok. It's hard to actually see what an alert looks like without creating one which means something is wrong.

The sensor I added for me it currently shows 0 I assume if there is an alarm it would be anything but 0. If we are lucky there's a text value to the alarm.

**Comment by barndawgie** [comment]
Next time I have an alarm I will post here before clearing it. I _believe_ what we will get is one of the alarm codes from the manual (see page #27): https://rmc-cdn.s3.amazonaws.com/media/uploads/iat/sites/36/2020/04/AP21681-UseAndCare.pdf

**Comment by barndawgie** [comment]
Any chance we can get this working with the new firmware model? Nothing related to alarms/alerts seems to be consumed from the bus looking at https://github.com/Daniel-dev22/esphome-econet/blob/312bb078755126d99d12d6c2d6cd4abb555f584a/components/econet/econet.cpp#L144C12-L144C15

Is it just a matter of looking for the right messages? I'm not sure how/where you guys figured out the protocol but I do references in the logs to `ALARMNUM` and `ALARM_01`.
