### ISSUE TITLE
CodeQL CPP Check Fails on All Check-Ins

### ISSUE THREAD

**Issue by barndawgie** [Daniel-dev22/esphome-econet#29]
I see the following in the log:
```
We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps. Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.14.3/x64/codeql/cpp/tools/autobuild.sh". Exit code was 1 and error was: cpp/autobuilder: Build will be attempted from '.' even though no build system was found there.
```

Is this fixable? Or should we remove/disable the check?

**Comment by Daniel-dev22** [comment]
It probably is fixable.

It's failing because I didn't set it up properly. If you know how to set it up prs are welcome. I didn't have time to keep messing with it. The goal is for GitHub actions running on each push to check code.
