### ISSUE TITLE
Inquiry: can this be extended to parse Lennox RSbus Communicating Protocol?

### ISSUE THREAD

**Issue by 42Network** [Daniel-dev22/esphome-econet#32]
Hello. I have a Lennox iComfort HVAC system using an S40 thermostat. I am wondering if any work has been done on decoding the Lennox RS-485 protocol, or if you have any clues about whether I would be successful doing so? I suspect your method of using a M5 RS-485 module to get packets might work for Lennox, but I have no idea how to go about deciphering the packets. I assume each vendor has some proprietary, possibly encrypted, protocol.

**Comment by Daniel-dev22** [comment]
> Hello. I have a Lennox iComfort HVAC system using an S40 thermostat. I am wondering if any work has been done on decoding the Lennox RS-485 protocol, or if you have any clues about whether I would be successful doing so? I suspect your method of using a M5 RS-485 module to get packets might work for Lennox, but I have no idea how to go about deciphering the packets. I assume each vendor has some proprietary, possibly encrypted, protocol.
> 
> 

Does Lennox use rs-485? Is there a port you can connect to? Each vendor does have proprietary stuff after the climate talk protocol fell apart. I am not sure if Lennox was ever apart of that protocol. If it was then it could be similar to this if not then it might be far off.

**Comment by Daniel-dev22** [comment]
If you have any additional questions I would consider joining the [discord](https://discord.gg/MtEsC77xRg) this repo is being archived in favor of consolidating code [here](https://github.com/esphome-econet/esphome-econet).
